# Site settings
title: Leon Aves | Web Developer
email: me@leonaves.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Essex based web developer and designer, Leon Aves.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://leonaves.github.io/" # the base hostname & protocol for your site
twitter_username: leon_aves
github_username:  leonaves

# Build settings
markdown: kramdown
exclude: [vendor]
